# Generated by Django 4.2.7 on 2023-11-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_rename_menu_menuitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='Inventory',
            field=models.SmallIntegerField(),
        ),
    ]
